serviceName: "${SERVICENAME}"

httpServer:
  port: "${HTTPSERVER_PORT}"
  env: "${HTTPSERVER_ENV}"
  basePath: "${HTTPSERVER_BASEPATH}"
  timeout: "${HTTPSERVER_TIMEOUT}"
  host: "${HTTPSERVER_HOST}"

logger:
  level: "debug"
  format: "console"

database:
  password: "${DATABASE_PASSWORD}"
  user: "${DATABASE_USER}"
  url: "${DATABASE_URL}"
  schema: "${DATABASE_SCHEMA}"
  db: "postgres"

kafka:
  addr:
    - "${KAFKA_ADDR}"
  producers:
    notificationSender_sentEvent:
      topic: notification-sender.sent-event
      async: false
      batchSize: 10
      batchTimeout: 100
# TODO: в качестве консюмер группы не юзать имя сервиса
  consume:
    groupId: "${KAFKA_CONSUME_GROUPID}"
    consumers:
      notificationSender_sentEvent:
        topic: notification-sender.sent-event

inbox:
  put: { }
  poll: { }
